### PR TITLE
Add ls option

### PR DESCRIPTION
**Pull request by tony**
#599 rebased

### CODE REVIEW

**Comment by tony** [comment]
@pythops Do you want to make your own pull request / redo the branch ? (So you get full credit for this?)

I can wait as long as you'd like

**Comment by pythops** [comment]
@tony   Just merge it :)
I'm more interested in making the tool better than getting the credits to flatter my ego ;)

**Comment by tony** [comment]
@pythops Merged! 

I updated tests and switched it to use glob (since it's easier on package maintainers downstream, `pathlib` exists in our `pyproject.toml`, but it's only a test dependency)

**Comment by tony** [comment]
@pythops Merged!  Thank you for the contribution and the tests!

I updated tests and switched it to use glob (since it's easier on package maintainers downstream, `pathlib` exists in our `pyproject.toml`, but it's only a test dependency)

**Comment by pythops** [comment]
@tony glad to contribute :)

**Pull request merged**
