### PR TITLE
Changes colors to be an int, not a string

### LINKED ISSUE #678: colors is compared as an int but set as a string
I am running tmuxp 1.7.2 on Arch Linux. When I attempt to load a workspace, I see the following output:
``` sh
% tmuxp load desktop
[Loading] /home/sam/dotfiles/shell/.config/tmuxp/desktop.yaml
Traceback (most recent call last):
  File "/usr/bin/tmuxp", line 33, in <module>
    sys.exit(load_entry_point('tmuxp==1.7.2', 'console_scripts', 'tmuxp')())
  File "/usr/lib/python3.9/site-packages/click/core.py", line 1134, in __call__
    return self.main(*args, **kwargs)
  File "/usr/lib/python3.9/site-packages/click/core.py", line 1059, in main
    rv = self.invoke(ctx)
  File "/usr/lib/python3.9/site-packages/click/core.py", line 1665, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/lib/python3.9/site-packages/click/core.py", line 1401, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/lib/python3.9/site-packages/click/core.py", line 767, in invoke
    return __callback(*args, **kwargs)
  File "/usr/lib/python3.9/site-packages/click/decorators.py", line 26, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/usr/lib/python3.9/site-packages/tmuxp/cli.py", line 1096, in command_load
    load_workspace(config[-1], **tmux_options)
  File "/usr/lib/python3.9/site-packages/tmuxp/cli.py", line 684, in load_workspace
    if builder.session_exists(session_name) and not append:
  File "/usr/lib/python3.9/site-packages/tmuxp/workspacebuilder.py", line 107, in session_exists
    exists = self.server.has_session(session_name)
  File "/usr/lib/python3.9/site-packages/libtmux/server.py", line 372, in has_session
    proc = self.cmd('has-session', '-t%s' % target_session)
  File "/usr/lib/python3.9/site-packages/libtmux/server.py", line 127, in cmd
    raise ValueError('Server.colors must equal 88 or 256')
ValueError: Server.colors must equal 88 or 256
```

Inspecting the variables using pdb (`python -m pdb /usr/bin/tmuxp load desktop`) reveals that `self.colors` is set to the string `'256'` (or `'88'` if the `-8` flag is passed) but libtmux is comparing the value against an integer literal (`256` or `88`).

### PR DESCRIPTION
**Pull request by sam-lunt**
This fixes #678 and #649

I edited the file on my system and confirmed that this fixes the issue.

### CODE REVIEW

**Comment by Iiridayn** [comment]
"If no type is provided, the type of the default value is used. If no default value is provided, the type is assumed to be STRING." https://click.palletsprojects.com/en/8.0.x/options/#basic-value-options - so, probably a bug on their part to overlook `flag_value` sorta is the default option; possibly lost in a refactor.

Also fixes #649, since #679 is a duplicate - not sure if this line will help link things.

**Comment by sam-lunt** [comment]
@Iiridayn thanks, I missed the existing issue. I edited the description so that both will hopefully be closed by this PR.

I agree that this seems like an oversight in click's logic. It's pretty unexpected that `flag_value=256` gets coerced into `'256'`.

**Comment by tony** [comment]
Is there any assurance this PR, or #649, won't break earlier click versions?

**Comment by tony** [comment]
Does this work with click 7?

**Comment by sam-lunt** [comment]
@tony yes, the `type=` keyword arg does exist in Click 7.x. See documentation for [`click.option` decorator](https://click.palletsprojects.com/en/7.x/api/#click.option), which forwards all keyword args to [`click.Option` class](https://click.palletsprojects.com/en/7.x/api/#click.Option).

**Comment by tony** [comment]
@sam-lunt Since we lock click at `<8` as of a few months ago,  I wonder if this is worked around via our pinning of click?

Is this still happening if you uninstall and reinstall?

Thanks for the links, and pardon my fogginess at their API docs, they had a "soft recalled" release in their API docs for a few years and that kind of challenged my trust with click. :P By the time I adopted click is was too late to remove argparse.

(Seriously considering just using `argparse` again, but that's for another time)

**Comment by sam-lunt** [comment]
@tony I'm using Arch Linux, which uses Click 8, despite the pin. That said, after upgrading to tmuxp 1.8.2, libtmux 0.9.0, and click 8.0.1, I'm no longer seeing this issue. Adding a break point to `/usr/lib/python3.9/site-packages/libtmux/server.py:118` shows that `self.colors` is now `256` instead of `'256'`. I'm not sure what changed, but it seems that the issue is resolved.

**Comment by tony** [comment]
@sam-lunt Thank you!  Nice if this is the case!

If you'd like you can close this PR for now, pending it comes up again (if it does we can reopen)

**Comment by tony** [comment]
The reason why is I am a bit concerned about updating click to 8.0 as other Linux distros aren't using it yet. I'm concerned about compatibility.

**Comment by tony** [comment]
Thank you @sam-lunt!   We will monitor this from here

**Comment by sam-lunt** [comment]
@tony I think that's a good point about Click 8, but I would suggest `click>=7` instead of `click>=7,<8`. As you can see with Arch Linux, they just ignored the `<8` part anyway. I would guess that other distros will likely take a similar approach: they won't choose to hold click back to `7.x` in order to satisfy tmuxp, so it's better to ensure that tmuxp works equally well with 7.x and 8.x (it seems like you are already trying to do this, so I'm mostly suggesting updating the requirements file to match your intentions)

**Comment by tony** [comment]
re: `click>=7` 

I will consider relaxing the constraint. I have a bit too much on plate at the moment - we are seeking maintainers if that's of interest to you: https://github.com/tmux-python/tmuxp/discussions/290

Also `click>=7,<9` (to prevent APIs from breaking unexpectedly)

**Comment by Iiridayn** [comment]
Click 8.0.1 fixed the flag type inference which impacted this package. https://click.palletsprojects.com/en/8.0.x/changes/#version-8-0-1. Before then, this patch was manually applied by the Arch Linux package maintainer - see https://bugs.archlinux.org/task/70841.

**Comment by tony** [comment]
@Iiridayn Excellent!  8.0.1 may have fixed this by side effect

I'm still considering loosening the click constraint as well.  There are trade offs. Looser versioning isn't necessarily better. Other package managers enforce these constraints and they actually protected them from being affected (once we locked `<8`).

It may open a can of worms for other package managers, and potentially open the door to _more_ issues from click. No fault of theirs, there's a huge amount of surface area to cover.  This example included was certainly harmless enough, but had ramifications downstream

**Comment by Iiridayn** [comment]
I personally feel that strong version constraints are valuable - for upstream dependencies which follow Semantic Versioning, it's easy enough to lock to version and check when a new major version is released for incompatibility with features you care about. Overly lax or unspecified version constraints can result in software breaking post-update, as seen twice now for this package in Arch, where the constraints were ignored.

For Click 8 (8.0.1 anyway) you seem solid to approve it if you don't use any of impacted features. Certainly for at least basic operation it appears to be running fine on Arch Linux systems.

**Comment by tony** [comment]
@Iiridayn and @sam-lunt : in tmux 1.9.2 I allowed click 8.0.x 

How's this work?

I'll keep an eye on issues track to see if anything breaks for other distros / users too

for now I made it `<8.1`. I am a bit scared to do `<9` because click's implicit side effects sometimes break semver (imo)

**Pull request closed without merging**
