### PR TITLE
Support -h help option to add user friendliness (and follow the de-facto standard)

### PR DESCRIPTION
**Pull request by GHPS**

### CODE REVIEW

**Comment by tony** [comment]
Thank you for the PR!  Can you rebase?

**Comment by tony** [comment]
Is it possible to add a test to `test_cli.py` too?

**Comment by GHPS** [comment]
Thanks for your reply!

>Thank you for the PR! Can you rebase?

Since the PR is just a single line of code changed it perhaps makes
sense to simply copy it over...

>Is it possible to add a test to test_cli.py too?

Yes - but currently there is no test targeting the help system (the `--help` option).
I'm not sure what would be the best test to ensure that the help system is working.
The help menu? That would have to change with every UI change.

**Comment by tony** [comment]
> Since the PR is just a single line of code changed it perhaps makes
sense to simply copy it over...

Of course, whatever you'd think would make a clean commit to merge :)

For the test: You can take a look in `test_cli.py` to see how we assert, You can assert the `stdout`, for instance, and check if `Usage:` is at the top for `-h, `--help`, etc. if it's too much effort, no problem i can take care of it.  :)

**Comment by GHPS** [comment]
I've just rebased the commit and created two tests to verify that --help and -h work correctly.

The changes are in PR#700.

**Comment by tony** [comment]
@GHPS What commands did you use to rebase? There's still a conflict

What does `git remote -v` show btw? I can give you the commands to run.

**Comment by GHPS** [comment]
> There's still a conflict.

Seriously? Or are you looking at the same old conflict (f4c9fc2)?

Please take PR700 to merge - it is based on the latest source base.

**Comment by tony** [comment]
Moved to #700

**Pull request closed without merging**
