### PR TITLE
Updating readability and technical info

### PR DESCRIPTION
**Pull request by OdinsHat**
I took you up on the offer to help on the project. I've done like the commit message says. Updated based on latest technical features. Readability and tidy up. Let me know if you want anything.

### CODE REVIEW

**Comment by tony** [comment]
@OdinsHat Nice!

**Comment by tony** [comment]
@OdinsHat Hi there, sorry about this!  Can I get another rebase?

I just merged #623 which moves us to a [poetry](https://python-poetry.org/) packaging setup and will runs the PR through GitHub actions.

**Comment by tony** [comment]
@OdinsHat Can you please rebase this?  I don't have permission to merge it due to conflicts

I'd like you to get credit for the PR itself (not only the commit)

I can also opt to cherry-pick the commits into master and resolve conflicts on my end - but I prefer you get full recognition in the pull request

**Comment by OdinsHat** [comment]
I'm really sorry Tony. I got this email at a bad time in my life. Did I
ever do the rebase as requested? Do you still need it?

**Comment by tony** [comment]
@OdinsHat Hi there

Sorry if you are (or were) going through something, I hope things it better on the front.

The situation regarding this file has changed, it's in markdown now: 
https://github.com/tmux-python/tmuxp/blob/master/docs/about.md

The diff is significant and it may be better to add the content again by starting from the most up to date `about.md` file.

I suggest this PR be closed and you make the changes in the new markdown format.  I could solve the changes myself but I want to make sure you get credit for the PR

**Comment by tony** [comment]
@OdinsHat To clean up PRs, since some time has passed since a response, I am closing this now but welcome you recreate the PR with our newest codebase

It's my fault for not getting to the PR fast enough, my bad on that. 

If you do make a second PR, please email me and I will give you first priority to review

**Pull request closed without merging**
