### PR TITLE
Pipenv update doc

### PR DESCRIPTION
**Pull request by rfoliva**
* Include section on pipenv.
* Clean up .rst files with trailing spaces, long lines and inconsistent section headers.

### CODE REVIEW

**Comment by rfoliva** [comment]
Updated doc on Pipenv ready for merge @tony .

**Comment by rfoliva** [comment]
@tony - I would be very happy to help.

Thanks for the extending the invitation!

**Comment by tony** [comment]
@rfoliva Invited.

**Comment by rfoliva** [comment]
@tony - Thanks.... I will start taking a look into it this evening. Thanksgiving weekend here in Canada! :)

**Comment by tony** [comment]
@rfoliva Sounds good. Enjoy your holiday! :)

**Comment by rfoliva** [comment]
@tony I checked and it seems I need to be given Admin or at least Write permissions in order to be able to handle issues and PRs within the organization.

Here is the link for reference:
https://help.github.com/articles/repository-permission-levels-for-an-organization/

Thanks!

**Pull request merged**
