### PR TITLE
Use XDG base directory specification for config files

### PR DESCRIPTION
**Pull request by anddam**

### CODE REVIEW

**Comment by tony** [comment]
@anddam Looks good to me. I'll take a look this weekend. :)

**Comment by anddam** [comment]
Thanks, I had a big fight with git and ended up squashing and re-creating the topic branches from my previous pull requests, that I have now deleted. The feature changes should be properly separated now.

**Comment by mcchrish** [comment]
@anddam @tony this is very neat change. Hope this feature can be merged and released soon.

**Comment by tony** [comment]
Mmm, and I'm late on my promise to look at it too... 

@anddam Can we get a rebase? (to run it through CI again)

**Comment by rfoliva** [comment]
Thanks @anddam for the contribution.

I have just merged it.

**Pull request merged**
