### PR TITLE
Adding Plugin System

### PR DESCRIPTION
**Pull request by joseph-flinn**
Adding most of the logic for the Plugin System from https://github.com/tmux-python/tmuxp/issues/530. I have done some initial manual testing and it seems to be working.

Design Decisions: 
- All plugin methods run after their tmuxp config counter parts (ie. the global `before_script` in the tmuxp config will run before anything in the `plugin.before_script` method)
- Require list type for plugins even if only a single plugin
- Assuming that the `plugin.on_window_create` method is referring to when tmuxp is creating new windows versus the user creating a new window in tmux
- Assuming that the `plugin.after_window_finished` method is referring to after the window is done being setup versus when the tmux user closes the window

Currently missing:
- [x] updated unit tests
- [x] updated documentation

### CODE REVIEW

**Comment by tony** [comment]
@joseph-flinn Try rebasing (I fixed an issue with poetry), running `poetry install` and then `make black isort`

**Review by tony — COMMENTED** [review]
@joseph-flinn Try rebasing (I fixed an issue with poetry), running `poetry install` and then `make black isort`

**Comment by tony** [comment]
Lets aim to get this in the next release (and last Python 2.7 release)

This will assure packaged versions of tmuxp on BSD/Linux and systems using python 2.7 have a plugin system.

**Comment by joseph-flinn** [comment]
Note: The bump in version is required for the extensive testing of the plugin system. The test plugins all depend on tmuxp version 1.6.0 (I believe this is the next release that will contain this feature?)

**Comment by tony** [comment]
> Note: The bump in version is required for the extensive testing of the plugin system. The test plugins all depend on tmuxp version 1.6.0 (I believe this is the next release that will contain this feature?)

Yes, this version bump and the constraint seems appropriate.

**Comment by tony** [comment]
@joseph-flinn Can you rebase this? (I know from email you're not around today)

**Comment by tony** [comment]
@joseph-flinn Can you try rebasing instead of merge? e.g. `git pull --rebase origin master` + `git push --force-with-lease` ?

**Comment by joseph-flinn** [comment]
> @joseph-flinn Can you try rebasing instead of merge? e.g. `git pull --rebase origin master` + `git push --force-with-lease` ?

Whoops, yep. I thought I did the rebase instead of the merge. I don't think I finished the complete mental context switch on Sunday

**Comment by joseph-flinn** [comment]
Oh, I just remembered that I used the `rebase` on github.com instead of doing it locally. I guess I won't do that again.

**Comment by tony** [comment]
@joseph-flinn technically the command (e.g. `git pull origin master --autostash`) depends on what `tmuxp-python/tmuxp` is set to

Since I don't know what your remotes are named, here is what it'd be if `tmux-python` and `joseph-flinn` are set:

`git remote add tmux-python git+ssh://git@github.com/tmux-python/tmuxp.git`
`git remote add joseph-flinn git+ssh://git@github.com/joseph-flinn/tmuxp.git`

Then:
`git pull tmuxp-python master --autostash`
`git push --force-with-lease -u joseph-flinn plugin-system`

**Comment by tony** [comment]
@joseph-flinn Nice! You pushed it seconds after I wrote that, I guess you figured it out before! 😊

**Comment by joseph-flinn** [comment]
Yeah, that merge was my bad. I tried "resolving the conflicts" through github.com last weekend instead of doing it locally and must of have either hit merge instead rebase.

**Comment by tony** [comment]
@joseph-flinn https://tmuxp.git-pull.com/history.html#tmuxp-1-6-0-2020-11-06

You can rebase again, there's a conflict

Let's aim to get this in tomorrow (Sunday latest)

Once its in master we will be able to dogfood it on our local machines

**Comment by joseph-flinn** [comment]
Sounds good. I'm planning on working on it most of tomorrow.

**Comment by tony** [comment]
@joseph-flinn If you'd like to rebase this you can

I will try to merge this in this afternoon/evening/tomorrow

**Comment by tony** [comment]
@joseph-flinn 

It's live :)

https://pypi.org/project/tmuxp/1.7.0/

https://tmuxp.git-pull.com/history.html#tmuxp-1-7-0-2021-01-09

**Pull request merged**
