### PR TITLE
Update installation methods in README.rst and in docs/quickstart.rst

### PR DESCRIPTION
**Pull request by jvcarli**
Update the relevant files with Homebrew installation method now that tmuxp is in Homebrew/homebrew-core@aff29be.

### CODE REVIEW

**Comment by tony** [comment]
@jvcarli Also shouted this out in our CHANGES file :)

**Comment by tony** [comment]
Now that tmuxp 1.8.0 is out we probably should update homebrew for that  :)

I made a [post release](https://www.python.org/dev/peps/pep-0440/#post-releases) on pypi to make sure its in the README and changelog.

**Comment by jvcarli** [comment]
I tried to update the formula and it was surprisingly easy.

The process:

1. `brew bump tmuxp`, which shows the latest available version of the package and if there's any open pull request for bumping the formula. The output:
 
    ```
    Current formula version:  1.7.2
    Latest Repology version:  1.7.2
    Latest livecheck version: 1.8.0.post0
    Open pull requests: none
    ```

2. `brew bump-formula-pr --strict tmuxp --version=1.8.0.post0` to update the formula and send a pull request to homebrew-core automatically.

However, I hadn't done 2 yet because I wanted to test the formula update locally. The package builds as expected, but the [assert test](https://github.com/Homebrew/homebrew-core/blob/c57879bf16e618855ee2b7b97cfd81ce7497127a/Formula/tmuxp.rb#L50) fails because it tries to match `1.8.0.post0` (which is used to make tmuxp local directory, I think Homebrew gets this from [PyPI](https://pypi.org/project/tmuxp/#history)) against  [`1.8.0post0`](https://github.com/tmux-python/tmuxp/blob/7448f348b10706b60a08cc5e6261c1a2c09b002c/tmuxp/__about__.py#L3) (without the dot before post) from `tmuxp --version`.

The other tests were successful.

This is almost nitpicking but it will make the tests fail in Homebrew CI and the formula update won't be accepted. How do you want to deal with this @tony? I don't think this test is necessarily bad, although is not specially useful for checking if tmuxp works correctly when installed with Homebrew, so I could remove it from the formula or you could update `__version__` in `__about.py__`.

**Comment by tony** [comment]
@jvcarli 

I will publish 1.8.1 for now. Standby

**Comment by tony** [comment]
1.8.1 is published: https://pypi.org/project/tmuxp/1.8.1/

**Comment by tony** [comment]
@jvcarli [1.8.1](https://pypi.org/project/tmuxp/1.8.1/) is live. Better now?

**Comment by jvcarli** [comment]
@tony Everything's working!

**Comment by jvcarli** [comment]
I had some issues with git trying to bump the formula automatically using `brew bump-formula-pr --strict tmuxp --version=1.8.1`. Tomorrow I'll fix then and submit a PR to homebrew-core.

**Comment by tony** [comment]
@jvcarli Sounds like a plan!

**Pull request merged**
