### PR TITLE
Add command for listing existing configurations

### PR DESCRIPTION
**Pull request by anddam**

### CODE REVIEW

**Comment by anddam** [comment]
The lines echoing workspace configurations should likely go outside the try block since they do not depend on the scandir execution.

**Comment by anddam** [comment]
I moved the output part outside the try block and made the docstring slightly more readable.

**Comment by tony** [comment]
Sorry for the late response, I am having issues keeping up with the project. I'm seeking maintainers @ https://github.com/tony/tmuxp/issues/290. If you (or someone you know) may be interested in helping maintain libtmux or tmuxp, feel free to contact me by email or in the https://github.com/tony/tmuxp/issues/290 issue.

In the mean time, if you're still interested in this PR, can you rebase it via ``git pull --rebase origin master`` and ``git push --force``?

**Comment by tony** [comment]
Closing and reopening (trying to trigger travis build)

**Comment by anddam** [comment]
Sure, but I need to sort out my own repo before that.

**Comment by anddam** [comment]
I rebased on top of your master branch.

**Pull request closed without merging**
