### PR TITLE
Update index.md

### PR DESCRIPTION
**Pull request by jcromero**
Fix typo

### CODE REVIEW

**Comment by tony** [comment]
@jcromero Thank you! Can you sign the CLA?

**Comment by jcromero** [comment]
Signed

**Comment by tony** [comment]
@jcromero I don't see it _yet_

image

**Comment by jcromero** [comment]
Nos?

**Comment by tony** [comment]
image

Looks good!

**Comment by tony** [comment]
Thank you @jcromero !

**Pull request merged**
