### PR TITLE
Add --log-file option to load command

### PR DESCRIPTION
**Pull request by joseph-flinn**
Adding the `--log-file` option to the `load` command. 

(As discussed over email. There isn't a specific issue for the addition)

### CODE REVIEW

**Review by tony — COMMENTED** [review]
Nice @joseph-flinn !

The logger does such a good job it preserves colors:

`tmuxp load ~/work/python/libtmux --log-file ~/mylog.log`
image

In another tab:

`cat mylog.log`
image


```
~ ❯ cat mylog.log
(INFO) [15:11:15] tmuxp.cli  [Loading] /home/t/work/python/libtmux/.tmuxp.yaml
```

1. Should we add an ability to control log level?  I don't think one is available is it?
2. Should we add an option to stripe formatting?

`cat` looks beautiful, but for the text itself in an editor:
image

```
^[[0m^[[32m^[[1m(INFO)^[[0m [^[[30m^[[2m^[[1m15:11:15^[[39m^[[0m] ^[[37m^[[2m^[[1mtmuxp.cli^[[39m^[[0m ^[[0m [Loading] /home/t/work/python/libtmux/.tmuxp.yaml
```

**Comment by joseph-flinn** [comment]
1. I think there is a way to set the log level from the `click.group` by including `--log_level <LEVEL>`. This should be passed through to `tmuxp_echo`. I did just notice that `--log_level` uses underscores (left over from all of the other logging code I assume). I'll change that over to a dash.
2. Hmm...I `click.unstyled` the message before logging it to the file. I wonder if the logger formatter that was already included with tmuxp has some coloring that is left over. We probably don't want the color if it is leaving the (bash?) color codes. Thoughts?

I also just remembered that I forgot to update the README and other supporting documentation. I'll go ahead and do that as well

**Comment by tony** [comment]
@joseph-flinn Sorry for the delay! I may be busy on the weekend for a week or two (errands on my end!)

Merged in v1.6.3 and v1.7.0a3!

1.6.3: http://localhost:8031/history.html#tmuxp-1-6-3-2020-11-22, https://pypi.org/project/tmuxp/1.6.3/

1.7.0a3: http://localhost:8031/history.html#tmuxp-1-7-0a3-2020-11-22, https://pypi.org/project/tmuxp/1.7.0a3/

**Comment by joseph-flinn** [comment]
No worries! I'll probably be a bit busy for the next couple weekends as
well, but will put some work in when I can.

**Comment by tony** [comment]
@joseph-flinn Sounds good!

**Pull request merged**
