### PR TITLE
Load config appending windows in current active session

### PR DESCRIPTION
**Pull request by emanuelhfarias**
I see some people requesting this feature (me included) https://github.com/tmux-python/tmuxp/issues/289 https://github.com/tmux-python/tmuxp/issues/373 and some even tried to add this functionality https://github.com/tmux-python/tmuxp/pull/374 https://github.com/tmux-python/tmuxp/pull/407 but those ideas never went from draft.

I decided to implement this feature maintaining the compatibility with features we already have (open attached and detached). The motivation to this feature is because I feel more productive seen everything I have opened as visible windows. I tried to use several sessions and **switch-sessions** using tmux shortcut _C-b s_ but I didn't get use to it (maybe I will try again in the future).

Summarizing what this PR adds:
When you try to **load** a config file within a current open tmux session it will ask you if you want to: 

1. create a new session and attach?
2. create a new session and detach?
3. load config appending windows in the current active session?

To maintain the compatibility I didn't change the question, I just added another option to the user.
> Already inside TMUX, switch to session? yes/no
Or (a)ppend windows in the current active session?
[y/n/a]:

If you anwser:
**Yes** it will attach
**No** will detach
**Append** will append windows in the same session

I also added the ability to _force append_ using the CLI:
`$ tmuxp load -a config`

I hope to see this feature in **tmuxp**. Who else's want? :point_up_2:

### CODE REVIEW

**Comment by MagicDuck** [comment]
Me needs this as well 😍

**Comment by Wesmania** [comment]
+1, it's really convenient to setup just a single window with a few panes without creating a new session.

**Comment by Wesmania** [comment]
It seems that the active session is not detected correctly. Something like this should work better:

```
    def find_current_attached_session(self):
        sid = self.server.cmd("display", "-pt", os.environ['TMUX_PANE'], "#{session_id}")
        return self.server.get_by_id(sid.stdout[0])
```

**Comment by nickwynja** [comment]
I also think it's helpful to switch to an existing session instead of throwing an error, like this: https://github.com/nickwynja/tmuxp/commit/8db90263ac10ee166154d6d44545fb63c6e6ba67

**Comment by tony** [comment]
@emanuelhfarias Hi there, sorry about this!  Can I get another rebase?

I just merged #623 which moves us to a [poetry](https://python-poetry.org/) packaging setup and will runs the PR through GitHub actions.

**Comment by WantGuns** [comment]
Is this PR still active ? I would love to get this feature merged. 
Awesome work with tmuxp btw

**Comment by tony** [comment]
@emanuelhfarias Can you rebase this?

**Comment by emanuelhfarias** [comment]
> @emanuelhfarias Can you rebase this?

yes

**Comment by emanuelhfarias** [comment]
I'm trying to rebase but the code has change a lot. It is difficult to solve all the conflicts and keep everything working. This PR is one year and a half old.
I'm not even using tmuxp anymore. If anyone wants this, the method that change the most is `def load_workspace()` from cli.py.

**Comment by tony** [comment]
@emanuelhfarias

Sure, someone can fork this PR and try to rebase it. (Or do it manually on top of master, without git's conflict tool)

Thank you once again for this PR, and sorry for the delay!
On 12/27/2020 2:40:38 PM, Emanuel H. Farias <notifications@github.com> wrote:
I'm trying to rebase but the code has change a lot. It is difficult to solve all the conflicts and keep everything working. This PR is one year and a half old.
I'm not even using tmuxp anymore. If anyone wants this, the method that change the most is def load_workspace() from cli.py.

**Comment by will-ockmore** [comment]
Hey everyone, I've opened a new PR #656 with these changes, unfortunately I wasn't able to rebase your work without difficult to resolve conflicts @emanuelhfarias - I've credited you in the PR itself as it's almost entirely your work, I just added a bugfix and some cleanup. Thanks for opening this PR! I've been looking for this functionality. Hoping we can get it merged in :crossed_fingers:

**Comment by will-ockmore** [comment]
This work has been merged in #656 :raised_hands:

**Pull request closed without merging**
