### PR TITLE
Added "-y" Option to convert command to directly convert the config

### PR DESCRIPTION
**Pull request by aRkedos**
I implemented the feature requested in #589. I ran all test except the one described in issue #620. 

I extensively tested the feature with a a lot of configs. I went with "-y" like requested in #589 but maybe it would be more concise to do `-f` / `--force` like PR #618 does with the freeze command.

### CODE REVIEW

**Comment by tony** [comment]
@aRkedos Hi there, sorry about this!  Can I get another rebase?

I just merged #623 / 937474a which moves us to a [poetry](https://python-poetry.org/) packaging setup and will runs the PR through GitHub actions.

**Comment by aRkedos** [comment]
Do You mean just a rebase that sqaushes the 4 commits into one or a rebase that is in sync with the current state of the master branch?

**Comment by tony** [comment]
@aRkedos  Hi there! Rebase in sync with the current master branch

**Comment by aRkedos** [comment]
Okay rebased it :) Would like to work on other issues / freature requests too, but don't want to do too much at the same time; so I'll wait for your feedback.

**Comment by tony** [comment]
Nice @aRkedos.  I made 2 contributions to the function, what do you think?

- Can you update the changelog?
- Document behavior in readme?

**Comment by aRkedos** [comment]
Ah that totally makes sense and removes the redundancies in the if branches. My Idea was to write a helper function which does the actual file writing which is called after confirmation (be it via prompt or via option). But this way is much clearer.

And I see why my tests which I wrote initially did not affect the code coverage (was my inexpierience with pytest), I was using the invoke method which is not necessary.

I will update the changelog and document the behaviour.

**Review by tony — APPROVED** [review]
Looks good to me!  Thank you @aRkedos !

**Pull request merged**
