### PR TITLE
Added support for -f flag to use non-default tmux config file

### PR DESCRIPTION
**Pull request by lins05**
Thanks for this awesome project! I find it's useful to use a specific tmux.conf when automating some tasks. Hopefully this would be useful for others too.

### CODE REVIEW

**Comment by TerraTech** [comment]
@tony Is there any chance this PR can be merged for next release?

I'm using the patch locally and it is working great so far.

**Comment by tony** [comment]
@TerraTech Hi there, sorry about this!  Can I get another rebase?

I just merged #623 which moves us to a [poetry](https://python-poetry.org/) packaging setup and will runs the PR through GitHub actions.

**Comment by tony** [comment]
@lins05

Hi, sorry for letting this go on so long, that's my fault.

Can you please rebase the PR and solve on the conflicts?

If there's no response I'll assume this is ok to close, but you'd be welcome to remake the PR in the future.

**Comment by TerraTech** [comment]
@tony  If @lins05 has fallen off the grid, would you accept the patch in a new PR from myself to get this merged in?  I ask because of the the `CLA` that needs to be signed, and I'm not sure how that works when someone else has authored the patch.

Overall, I'd like to remove the custom patch from my portage build routines.

**Comment by paulmsmith** [comment]
New machine and just got to this problem. Would love this to be resolved and merged.

**Comment by tony** [comment]
@paulsmith @TerraTech

`-f` already works with tmuxp. What makes this different?

e.g. Have you tried `tmuxp load` with `-f`? `tmuxp load --help`?

**Comment by tony** [comment]
This was in since 1.7.1, Feb 3, 2021, ee8c6e224a2ee90e275907ff1a269c7c930d5070 

Let me know if it works if you try it

Note that this only works for newly started tmux servers (it's an `-f` passthrough), it doesn't run `source-file` to apply a config on    servers that are already started. That would be a different PR etirely

**Comment by paulmsmith** [comment]
It does? I didn't realise @tony, I will check. I just now ended up symlinking .tmux.conf to my dotfiles directory, will revert. Thank you for the swift reply.

**Comment by paulmsmith** [comment]
Ah, I saw that:

2022-02-05 at 18 51 00

But my tired mind totally misread it I think.

**Comment by paulmsmith** [comment]
@tony Forgive my lack of experience, but should it be something like: 
```
tmuxp load personal -f ~/.files/.tmux.conf
```

**Comment by tony** [comment]
@paulmsmith I did a test and yes, like that.

`tmuxp load ~/projects/project-a -f ~/example-tmux-config.conf`

And this only worked on new sessions.

For subsequence sourcing, you could try `tmux source-file ~/path-to-tmux-config.conf` in the `shell_command_before` in the session or window level and see if that works, but note that due to the way tmux works, some config settings are server-wide.

Does this resolve your question btw?

If it does, are you willing to ask it in https://github.com/tmux-python/tmuxp/discussions and answer it?  Maybe that can make it easier for people in a similar situation

**Comment by paulmsmith** [comment]
> Does this resolve your question btw?

It does, thank you @tony I have attempted adding question and answer discussion thread: [How to use tmux with custom a `tmux.conf` file location when using tmuxp?](https://github.com/tmux-python/tmuxp/discussions/736)

**Comment by tony** [comment]
@paulmsmith this additional discussion thread is wonderful! Thank you!

**Comment by tony** [comment]
@lins05 

I am closing this since we already have this in master.

You made this PR first. I missed it. A subsequent PR at #665 added it, and when going through the queue, that was appeared first.

To be clear: me not getting to your PR is my fault. I apologize for that

I promise if you ever do make another contribution here I will make you first priority.  You can email me the PR directly so its certain I ese it.

**Pull request closed without merging**
