### PR TITLE
Add start-directory argument when creating new tmux session

### PR DESCRIPTION
**Pull request by anddam**
Fix enconding name as well.

### CODE REVIEW

**Comment by anddam** [comment]
This breaks with `TMUX_VERSION <= 1.8`, should I catch that in code or is it safe (where "safe" actually means easier) to just require a minimum tmux version of `1.9`?

**Comment by tony** [comment]
@anddam Can you rebase this?

I just merged #623 which moves us to a [poetry](https://python-poetry.org/) packaging setup and will runs the PR through GitHub actions.

**Comment by tony** [comment]
@anddam Is this the same as #197?

**Comment by anddam** [comment]
> @anddam Is this the same as #197?

No, #197 was better. I am closing this.

**Comment by tony** [comment]
Thank you @anddam!

**Pull request closed without merging**
