### PR TITLE
Add support for renaming session during load

### PR DESCRIPTION
**Pull request by kenwarner**
Addresses #206

### CODE REVIEW

**Comment by tony** [comment]
@kenwarner Sorry for the delay,

Can you update and add a test case for this?

**Comment by tony** [comment]
Sorry for the late response, I am having issues keeping up with the project. I'm seeking maintainers @ https://github.com/tony/tmuxp/issues/290. If you (or someone you know) may be interested in helping maintain libtmux or tmuxp, feel free to contact me by email or in the https://github.com/tony/tmuxp/issues/290 issue.

In the mean time, if you're still interested in this PR, can you rebase it via ``git pull --rebase origin master``?

**Comment by tony** [comment]
@kenwarner Can you rebase this?

I just merged #623 which moves us to a [poetry](https://python-poetry.org/) packaging setup and will runs the PR through GitHub actions.

**Comment by tony** [comment]
@kenwarner : is it possible you could give this a rebase?  Sorry for getting to this late!

There is another PR by @joseph-flinn at #623 and I received an email from him.

**Comment by kenwarner** [comment]
@tony sorry I just noticed this. I'll do the rebase shortly 👍

**Comment by tony** [comment]
@kenwarner Do you want to continue with this PR?  There is a conflict that needs to be solved via rebase

**Comment by tony** [comment]
@kenwarner I am closing this now, but if you have interest in making it again please feel free to make one

It's my fault for not getting to the PR in a timely fashion, my bad on that. 

If you do make a PR in the future please email me so I can look at it first thing

**Pull request closed without merging**
