### PR TITLE
Add command to list layouts in config directory

### PR DESCRIPTION
**Pull request by anddam**

### CODE REVIEW

**Comment by anddam** [comment]
Job [no. 2481.11](https://travis-ci.org/tmux-python/tmuxp/jobs/442100701) failed due to timeout, can an owner of tmux-python/tmuxp relaunch just that or the whole build from this issue?

I don't have any option for that.

**Comment by tony** [comment]
@anddam Eek. I made a mistake here. I didn't look over this PR, a newer one came in with this as a change, and I took it.

Yikes. I'm sorry. I've been busy and haven't had time to look at these, I only have so much attention I can give to PRs (I took on too many projects, it seems)

I think this was done via #599 (#616), though technically you were first.

I'm not quite sure what to do - he just happened to ping me more when I looked

I can give you credit in the CHANGE log if you'd like.  If you'd like to improve the listing feature you can also that if you want.

If there's nothing to add, we can close this.

I apologize again for this

**Comment by anddam** [comment]
> If there's nothing to add, we can close this.

> I apologize again for this

No need to apologize, we can close this.

**Comment by tony** [comment]
@anddam 

When 1.5.0 was released #404 wasn't mentioned in changelog until 2 days ago: https://github.com/tmux-python/tmuxp/commit/d7d444e161c0c47e75d44cb48c1b6194d1ed71a5

Thank you!

**Pull request closed without merging**
