### PR TITLE
Update Vi copy and paste key bindings for tmux 2.4

### PR DESCRIPTION
**Pull request by fszymanski**

### CODE REVIEW

**Comment by tony** [comment]
What do you think of this: https://github.com/tony/tmux-config/blob/4e6c638/.tmux.conf#L92

**Comment by fszymanski** [comment]
I like it, but I'm afraid that it may be less readable for beginners. On the other hand, we can assume that someone who uses `tmux` is a more advanced user.

**Comment by tony** [comment]
My concern is that readers could copy and paste that configuration in and, as you said, since they're beginners, if they didn't comment it out manually, it could break.

Any idea how'd you like to approach? Perhaps mentioning to check `$ tmux -V` and splitting up the copy-paste thing into separate codeblocks depending on the version?

**Comment by fszymanski** [comment]
I see your point! Maybe splitting the code would be the best solution.

**Comment by tony** [comment]
Go ahead an give it a shot.

**Comment by tony** [comment]
Sorry for the late response, I am having issues keeping up with the project. I'm seeking maintainers @ https://github.com/tony/tmuxp/issues/290. If you (or someone you know) may be interested in helping maintain libtmux or tmuxp, feel free to contact me by email or in the https://github.com/tony/tmuxp/issues/290 issue.

In the mean time, if you're still interested in this PR, can you rebase it via ``git pull --rebase origin master`` and ``git push --force``?

**Comment by tony** [comment]
@fszymanski Can you rebase this?

I just merged #623 which moves us to a [poetry](https://python-poetry.org/) packaging setup and will runs the PR through GitHub actions.

**Comment by tony** [comment]
@fszymanski 

Sorry for any inconvenience caused on my part. I let the PR go on too long. That is my fault.

Can you please remake this PR with the newest master?

Since you made this change the doc is now in markdown: https://github.com/tmux-python/tmuxp/blob/b9f35df/docs/about_tmux.md

I will close this for now but please feel free to make a new PR off master.

**Pull request closed without merging**
